<?php


namespace Tests\Feature\Controllers\Api;


use App\Http\Controllers\Api\IndexController;
use Tests\TestCase;

class IndexControllerTest extends TestCase
{

    protected $controller;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        if(!$this->controller) {
            $this->controller = new IndexController();
        }
    }

    public function testIndex()
    {
        $dummyRespond = [
            'page' => 'index',
            'type' => 'api'
        ];

        $res = $this->get('/api/');

        $this->assertJson($res->content());
        $res->assertStatus(200);
        $res->assertJson($dummyRespond);
    }
}
